### ISSUE TITLE
Setup infrastructure

### ISSUE THREAD

**Issue by dmcrodrigues** [babylonhealth/Wall-E#1]
Our main infrastructure will be composed by a server listening for events, received through WebHooks, so our first step should focus in picking a Server-Side Swift framework and bootstrap an application that should be deployed and accessible through an URL and ready to receive events.

While we should aim to support different providers, like GitLab, for now we should focus in supporting GitHub to speed up development.

## Security

Security is critical so we need to ensure that any payload received is coming from the provider we are expecting. GitHub supports a [secret token](https://developer.github.com/webhooks/securing/) which can be defined and used to certify the origin of the information.

## Backlog

- [x] Prepare the repository with `.gitignore`, `LICENSE` files
- [x] Create a web application
- [x] Setup CI to build and run all the tests
- [x] Prepare the logging infrastructure to log any incoming calls
- [x] Host the application in Heroku
- [x] Setup the infrastructure to certify the origin of any incoming payload
- [x] Receive [pull request events](https://developer.github.com/v3/activity/events/types/#pullrequestevent) from GitHub

This should give us all the infrastructure needed to shift our focus into the actual implementation of the bot.

**Comment by dmcrodrigues** [comment]
Infrastructure is now in place.

**Comment by RuiAAPeres** [comment]
Beautiful.
