### ISSUE TITLE
There's no good way to check Steve's queue

### ISSUE THREAD

**Issue by bh-pwestmeyer** [babylonhealth/Wall-E#11]
Right now I'm waiting hours to see my merge complete or error out. This has already cost me 24+ hours of development time. We need to have an ETA for Steve builds and a way to keep track of the queue.

**Comment by karabatov** [comment]
Either a page showing the queue and/or a Slack command to show it would be a-ma-zing!

**Comment by iTomkinas** [comment]
@bh-pwestmeyer actually if you open bot link it shows the queue

**Comment by danspndl** [comment]
I think this has been resolved, we have both the site and the menubar app to monitor the queue (#36)
