### ISSUE TITLE
Setup a workflow to deploy changes automatically

### ISSUE THREAD

**Issue by dmcrodrigues** [babylonhealth/Wall-E#5]
CircleCI supports [workflows](https://circleci.com/docs/2.0/workflows/) which can be used to deploy changes automatically. Any changes made should be deployed after being built and tested.

#### Backlog

- [x] Define a job to *build* the module for release
- [x] Define a job to *test* the app
- [x] Define a job to *deploy* the app
- [x] Execute the workflow every time a pull request is merged in `master`

**Comment by dmcrodrigues** [comment]
An alternative option can be @ilyapuchka's [solution](https://github.com/ilyapuchka/SwiftGitHubAction) to use GitHub Actions.

**Comment by dmcrodrigues** [comment]
This was greatly done already by @RuiAAPeres.

**Comment by RuiAAPeres** [comment]
![](
![image](https://user-images.githubusercontent.com/949286/59068158-478e5f80-8868-11e9-9b1d-270c38839abb.png)
)
![image](https://user-images.githubusercontent.com/949286/59068160-48bf8c80-8868-11e9-84eb-70b96eaac4ef.png)
